name: Releases
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          path: main
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Linux AMD64
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main && GOOS=linux GOARCH=amd64 go build -o bin/AMD64-Linux-crane-${{ github.event.inputs.version }} main.go
      - name: Build Darwin AMD64
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main && GOOS=darwin GOARCH=amd64 go build -o bin/AMD64-DARWIN-crane-${{ github.event.inputs.version }} main.go
      - name: Build Darwin ARM
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main && GOOS=darwin GOARCH=arm go build -o bin/AMD64-DARWIN-crane-${{ github.event.inputs.version }} main.go
      - name: release 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}